version: '3'
services:
  mopidy:
    image: jaedb/iris
    volumes:
      - ../music:/var/lib/mopidy/media:ro
      - ../playlists:/var/lib/mopidy/playlists:ro
      - ../netdj-configs/mopidy.conf:/config/mopidy.conf:ro
      - ./mopidy-entrypoint.sh:/entrypoint.sh:ro
    depends_on:
      - icecast

  icecast:
    image: infiniteproject/icecast
    env_file: ../netdj-configs/icecast-env
    volumes:
    - ../netdj-configs/icecast.xml:/etc/icecast.xml:ro
    - ./silence.mp3:/usr/share/icecast/web/silence.mp3:ro

  bot:
    image: node
    user: node
    working_dir: /home/node/app
    volumes:
      - ../mopidy-slack-bot:/home/node/app:ro
    command: "npx nodemon"
    ports:
      - 8765:8765
    env_file: ../netdj-configs/bot-env
    depends_on:
      - mopidy

  web:
    image: nginx:mainline-alpine
    volumes:
      - ../netdj-configs/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ../netdj-configs/htpasswd:/etc/nginx/htpasswd:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    ports:
      - 80:80
      - 443:443
    depends_on:
      - mopidy
      - icecast
      - bot
