version: '3'
services:
  bot:
    environment:
      - NODE_ENV=production
    command: "npm start"

  web:
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ../netdj-configs/extra-ssl.conf:/etc/nginx/extra-ssl.conf:ro
    ports:
      - 443:443
